name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: bot-never-sleep
        author_email: botcircleci@gmail.com
        message: "Add build result[skip ci]"
        add: "*.crx"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: true